version: "3"

services:
    crud-person:
      build: 
        context: ./
      restart: unless-stopped
      ports:
        - 1323:1323
     
    rabbitmq:
      image: rabbitmq:3.8.9-management-alpine
      container_name: 'rabbitmq'
      ports: 
        - 5673:5673
        - 15673:15673
      volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
      restart: unless-stopped

   

      
